// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApkgh1YrUb4K6rDJgv-4xlW5LZgZaJ144',
    appId: '1:88407096271:web:a9cc4725bc4222d0d4b0ba',
    messagingSenderId: '88407096271',
    projectId: 'testest-38c21',
    authDomain: 'testest-38c21.firebaseapp.com',
    storageBucket: 'testest-38c21.firebasestorage.app',
    measurementId: 'G-PVLGX0MSZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0NFseWaiX-1jJaNb81lwa96FtfOmszDY',
    appId: '1:88407096271:android:b483a6e7e912f9d9d4b0ba',
    messagingSenderId: '88407096271',
    projectId: 'testest-38c21',
    storageBucket: 'testest-38c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtvq_Vdo9ksZAXJjKgCxEa06VMwVMOqIc',
    appId: '1:88407096271:ios:72b44fb7bd182bdcd4b0ba',
    messagingSenderId: '88407096271',
    projectId: 'testest-38c21',
    storageBucket: 'testest-38c21.firebasestorage.app',
    iosBundleId: 'com.example.appExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtvq_Vdo9ksZAXJjKgCxEa06VMwVMOqIc',
    appId: '1:88407096271:ios:72b44fb7bd182bdcd4b0ba',
    messagingSenderId: '88407096271',
    projectId: 'testest-38c21',
    storageBucket: 'testest-38c21.firebasestorage.app',
    iosBundleId: 'com.example.appExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApkgh1YrUb4K6rDJgv-4xlW5LZgZaJ144',
    appId: '1:88407096271:web:b4c2b96f20f2cdc9d4b0ba',
    messagingSenderId: '88407096271',
    projectId: 'testest-38c21',
    authDomain: 'testest-38c21.firebaseapp.com',
    storageBucket: 'testest-38c21.firebasestorage.app',
    measurementId: 'G-3JJS9Y19JD',
  );
}
